version: "3.7"

services:
  admin-panel:
    build: 
      dockerfile: admin-panel-dockerfile
    restart: always
    hostname: admin-panel
    ports:
      - "80:80"
    command: [nginx,"-g","daemon off;"]

